services:
  - type: web
    name: fullstack-pj1-backend
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    rootDir: backend
    envVars:
      - key: MONGO_URI
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FRONTEND_URL
        value: https://fullstack-pj1-fd.netlify.app
